version: '3.3'
services:
  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - swarm_internal
    logging:
      driver: json-file
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        reservations:
          cpus: '0.05'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 64M
  app:
    image: swarmpit/swarmpit:latest
    environment:
      SWARMPIT_DB: http://db:5984
    ports:
     - 888:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - swarm_internal
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: couchdb:2.3.0
    volumes:
     - db-data:/opt/couchdb/data
    networks:
     - swarm_internal
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '0.15'
          memory: 256M
        limits:
          cpus: '0.3'
          memory: 512M
networks:
  swarm_internal:
    external: true
volumes:
  db-data:
    driver: local
