version: '3.3'
services:
  pihole:
    image: pihole/pihole:latest
    extra_hosts:
     - cloud.dragon-bytes.com:LOCAL_IP
     - swarm.dragon-bytes.com:LOCAL_IP
     - pihole.dragon-bytes.com:LOCAL_IP
    environment:
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      ServerIP: LOCAL_IP
      TZ: America/New_York
      WEBPASSWORD: REMOVED
      WEB_PORT: '8080'
    ports:
     - '53:53'
     - 53:53/udp
     - 8080:8080
    volumes:
     - /var/log/pihole:/var/log/
     - pihole_dnsmasq:/etc/dnsmasq.d/
     - pihole_pihole:/etc/pihole/
    networks:
     - swarm_internal
    logging:
      driver: json-file
    deploy:
      restart_policy:
        delay: 1s
networks:
  swarm_internal:
    external: true
volumes:
  pihole_dnsmasq:
    external: true
  pihole_pihole:
    external: true
